### ISSUE TITLE
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name

### ISSUE THREAD

**Issue by raosuj** [spekframework/spek-android-example#1]
Hi, I am running into this issue when I try running the test.

`WARNING: TestEngine with ID 'spek' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: org.spekframework.speksample.CalculatorSpec
	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:71)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:70)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:79)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
`
PS: Seeing this issue only on canary android studio 3/3.1. Stable 3.0 works fine, thanks

**Comment by radityagumay** [comment]
@raosuj hi, please take a look my PR https://github.com/spekframework/spek-android-example/pull/2, if this solve you issue, please close this. thanks

**Comment by radityagumay** [comment]
@raniejade as a new PR this issue should closed.
